// Copyright © 2022 - 2025 Attestant Limited.
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package rest

import (
	"encoding/json"
	"net/http"
)

// APIResponse is a response generated by the REST API.
type APIResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message,omitempty"`
}

// sendResponse is a helper to send a JSON response.
func (s *Service) sendResponse(w http.ResponseWriter,
	statusCode int,
	headers map[string]string,
	resp any,
) {
	if resp == nil {
		// No response to send.
		w.WriteHeader(statusCode)

		return
	}

	data, err := json.Marshal(resp)
	if err != nil {
		s.log.Error().Err(err).Msg("Failed to marshal response")
		w.WriteHeader(http.StatusInternalServerError)

		return
	}

	w.Header().Set("Content-Type", "application/json")
	for k, v := range headers {
		w.Header().Set(k, v)
	}
	w.WriteHeader(statusCode)
	_, err = w.Write(data)
	if err != nil {
		s.log.Error().Err(err).Msg("Failed to write response")

		return
	}
}
