name: golangci-lint
on:
  push:
    branches:
    - master
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          cache: false
          go-version: '1.25.1'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: 'latest'
          args: '--timeout=60m'
          skip-cache: true
